eureka:
  client:
    fetch-registry: true
    register-with-eureka: true
    service-url:
      defaultZone: http://localhost:8080/eureka
server:
  port: 9001
spring:
  application:
    name: Medication-Service
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    password: examly
    url: jdbc:mysql://localhost:3306/MedicationAdherenceRemindersDB
    username: root
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
